# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "u95bw8pxdOvvahHrgsEi2zX2cX3YngSFO3HHYudC8M1n1EWsrNCXdb3f+1x/lZl0aC/7KSUOH4VKnUBBb2fAGSdUKkylguwekMuQ6jQCSr2jon+wEdV4ckxcVR+VLiB807+2fSRhPbbYRFUj/2laRByqkZqjPXHwiMVCf7FBBEmh+S3gdnkmpCj11beT0Dwf00CdGtp+jew3pA3Xf0jP5kbVEzceKxofF5yOEu8njEejMHADbJweiidmwU2PzXs7+ersbSwI1osV0WtN4WGCQd3f7ZZlbQV6a4jsSATA34Wnq+ME/PkXzjyS/6uIPrQkI/KDN0A5xRielEmaIuwIL7014cCSbrm13Sqgp7CMgpsRX6GUmTEgtLXf0Q9LlK8EOdfyRoUnKppuiQpq2CuocZWFqtfV+PZXADcEzboPZwDRSDFeFRDAe+0EFYjvkAZNtEvSZ67flhVpF4CZ8q/wX5xxu2+r2O/F21Yw/v/eUXnxwGVYhZ2983WuRjvZn/kHLain8Pal8MA3t1R5AahUBnmXUa5w8BMKSVDyGeQ9V6FrSkTOgjrUVnuxKsyiUHl8ecVDPDslkMEUAeOLu3IakFl9Eh2jRhoLOcctsFnJx5sbORYap5KicJQ3ZlyKOJiHiYZz7XKT0TYD58pG2ULKARZeIYwnQCZmN4/gmcCobY0="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_python3.6 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_python3.7 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_python3.8 UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi